<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input-t-field-318</name>
   <tag></tag>
   <elementGuidId>3e610ff0-bf28-45f4-abd3-e209ab66e62e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.vaadin-text-field-container > #vaadin-text-field-input-0 > slot[name=&quot;input&quot;] > input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vaadin-text-field-input-0']/slot[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34381505-57b2-4c21-ae79-190d26caafae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>3df2b6e2-baf4-40c7-9f16-66d225cc1f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>86d9f363-3f1b-416b-ab61-b87a7cedbe3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>vaadin-text-field-label-0 vaadin-text-field-input-0</value>
      <webElementGuid>7c3e92e0-4de0-457d-9238-9c7fe60847f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;vaadin-text-field-container&quot;]/div[@id=&quot;vaadin-text-field-input-0&quot;]/slot[2]/input[1]</value>
      <webElementGuid>a0ca147a-7e44-4a80-9463-402be74ec0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/mockbank/Page_Sign Up/vaadin-text-field</value>
      <webElementGuid>b01bbd24-c70c-45f9-84a2-b6060f418591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>16c6e146-2428-43bf-a06d-5aef31197cfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vaadin-text-field-input-0']/slot[2]/input</value>
      <webElementGuid>719fb74f-5535-4355-875d-5d446234a82e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
