<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PRICING</name>
   <tag></tag>
   <elementGuidId>7194e9ff-118e-40c3-ae25-03be581e94a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'PRICING')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>084a5342-14d8-49e0-9529-e596b634d5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pricing</value>
      <webElementGuid>c95923d1-88a1-4a7a-b91b-c49d4b2566c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link w-nav-link</value>
      <webElementGuid>1b7dcb5d-6e9e-49a1-a7af-e4b911c607a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PRICING</value>
      <webElementGuid>1eebbf4c-0257-495c-b3c8-da8855acff54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;w-mod-js wf-montserrat-n1-active wf-montserrat-n3-active wf-montserrat-n2-active wf-montserrat-n6-active wf-montserrat-n8-active wf-montserrat-n5-active wf-montserrat-n7-active wf-montserrat-n4-active wf-montserrat-n9-active wf-sourcesanspro-n4-active wf-sourcesanspro-n2-active wf-sourcesanspro-n3-active wf-montserrat-i4-active wf-montserrat-i2-active wf-montserrat-i8-active wf-montserrat-i9-active wf-montserrat-i3-active wf-montserrat-i5-active wf-montserrat-i7-active wf-montserrat-i1-active wf-montserrat-i6-active wf-sourcesanspro-n9-active wf-sourcesanspro-n7-active wf-sourcesanspro-n6-active wf-sourcesanspro-i4-active wf-active&quot;]/body[1]/div[@class=&quot;navbar purple w-nav&quot;]/div[@class=&quot;w-container&quot;]/nav[@class=&quot;nav-menu w-nav-menu&quot;]/a[@class=&quot;nav-link w-nav-link&quot;]</value>
      <webElementGuid>d71268a3-a9b8-4a1f-8b43-c26a4be54c8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PRICING')]</value>
      <webElementGuid>e9be179d-281b-441d-a08a-eed37a2a2989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[1]/following::a[3]</value>
      <webElementGuid>a142843d-178a-4392-8fb3-de03185f4eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resources'])[1]/following::a[4]</value>
      <webElementGuid>114b0f74-a586-407d-a703-d601f31a47c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::a[1]</value>
      <webElementGuid>5651adda-3574-4db7-b266-aa8d37a98286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='signup'])[1]/preceding::a[2]</value>
      <webElementGuid>867977ac-47d2-4051-9f12-5c6b3a015d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PRICING']/parent::*</value>
      <webElementGuid>c6e670f4-3192-4128-bb49-5e778cd2d05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pricing')]</value>
      <webElementGuid>6f7d4832-57c8-4e9d-8e03-5b8d75bb5d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>55bc5f44-5e95-4260-8c47-a1921abea665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pricing' and (text() = 'PRICING' or . = 'PRICING')]</value>
      <webElementGuid>84ec2d28-46f3-4c61-aac2-77691c099b28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
