<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Developers</name>
   <tag></tag>
   <elementGuidId>b9f88e0e-c936-4c11-8c70-b248282806aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#w-dropdown-toggle-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-dropdown-toggle-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ab35ceb-cbfe-4ebd-9301-1bc083efc3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link dropdown-toggle w-dropdown-toggle</value>
      <webElementGuid>f6828425-4f56-4df3-b124-52353cb1d15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>w-dropdown-toggle-1</value>
      <webElementGuid>29ccfbc6-e6bb-4c9c-b908-5377be4da1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>w-dropdown-list-1</value>
      <webElementGuid>3f9539e2-cf04-4c0d-9867-f378d03d8e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>9fd18ede-c2bc-4227-895a-1e3cc67c259f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5bb14c19-d560-44ca-b2ee-c422ff4cccdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7eeb3b1a-df17-40a1-9a2f-0dbd33c30d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5c1edbfe-81fb-48ba-af20-f1135dd1b13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Developers</value>
      <webElementGuid>d7239a2f-308a-4860-89a4-0835f7208693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-dropdown-toggle-1&quot;)</value>
      <webElementGuid>5e35b817-1510-460f-9ab0-09970bfe876c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='w-dropdown-toggle-1']</value>
      <webElementGuid>8cccc30d-e3cf-4f8a-8b68-a262ea2acd9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UK Open banking'])[1]/following::div[2]</value>
      <webElementGuid>a7f19658-ebeb-432e-9857-3fc2e6463ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PSD2 Berlin Group'])[1]/following::div[2]</value>
      <webElementGuid>cb7a1572-09d5-4097-86ae-cdbfd25295d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Internal API'])[2]/preceding::div[3]</value>
      <webElementGuid>3b3fff12-970c-4e2e-b65a-7fd7d2ed119d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div[2]/div</value>
      <webElementGuid>e3d18846-573e-43e1-a3e1-80ebee3812c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'w-dropdown-toggle-1' and (text() = 'Developers' or . = 'Developers')]</value>
      <webElementGuid>7cdf547e-350f-47bf-a7fb-d070d5f21f08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
