<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_sign up</name>
   <tag></tag>
   <elementGuidId>1e40991b-9172-4836-807e-b52f739dbb45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#w-tabs-0-data-w-pane-1 > div.pricing-row.w-row > div.pricing-column.w-col.w-col-4 > div.white-pricing-block > div.pricing-block-content-wrapper.bottom > a.button-dark.white-pricing-button.w-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-tabs-0-data-w-pane-1']/div/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eed356a2-b0f2-4386-b1be-9a47ef8349aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://app.mockbank.io/signup</value>
      <webElementGuid>b476a215-e8b0-4186-bb91-a62c2581b428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>bce439bc-c210-4227-8fcb-ccac028a528c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-dark white-pricing-button w-button</value>
      <webElementGuid>b2d64ef7-de8a-4b80-9b71-980f77816ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sign up</value>
      <webElementGuid>5b016924-a97f-4b1e-ad5e-7c2eb3d57bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-tabs-0-data-w-pane-1&quot;)/div[@class=&quot;pricing-row w-row&quot;]/div[@class=&quot;pricing-column w-col w-col-4&quot;]/div[@class=&quot;white-pricing-block&quot;]/div[@class=&quot;pricing-block-content-wrapper bottom&quot;]/a[@class=&quot;button-dark white-pricing-button w-button&quot;]</value>
      <webElementGuid>f1631a1f-a564-4b58-880d-d6b0fb6f8a36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-tabs-0-data-w-pane-1']/div/div/div/div[2]/a</value>
      <webElementGuid>e01c8f43-c228-4982-8d74-2002bc1142c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'sign up')])[2]</value>
      <webElementGuid>ce06d401-78bc-4213-986f-ec7f7d51d5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Per year'])[1]/following::a[1]</value>
      <webElementGuid>b2adfd17-5265-4540-90c8-ca367ed1f632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€0.00'])[2]/following::a[1]</value>
      <webElementGuid>20aa62c6-db88-4bd9-8b12-be6295171789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Growth'])[2]/preceding::a[1]</value>
      <webElementGuid>d34c834e-28ad-4f9f-9ba4-c2d26db44830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€287.50'])[1]/preceding::a[1]</value>
      <webElementGuid>b12d7ac8-16dc-464e-aeb0-4c61bdc6b932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://app.mockbank.io/signup')])[4]</value>
      <webElementGuid>dfd8007c-faf0-4935-b7b9-88cf6a67373f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/a</value>
      <webElementGuid>79c797e1-dae3-4473-971b-3f2981c09144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://app.mockbank.io/signup' and (text() = 'sign up' or . = 'sign up')]</value>
      <webElementGuid>877ae2ad-1241-4b87-a27f-d1bb2f8a5e01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
